### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by odysseus1973** [azhmur/xxHash3#1]
Hello!

Thank you for great work.
How about add streaming support to XXHash?

Thanks!

**Comment by azhmur** [comment]
This is quite complex task to do considering all possible performance issues. I had postponed this work initially.
I can't give you any estimates if it would be done in near future, right now.

On same time you can check MS backed implementation: https://github.com/dotnet/runtime/tree/main/src/libraries/System.IO.Hashing/src/System/IO/Hashing

They did streaming support for XXH32 and XXH64 and now actively implementing XXH3, so they can have XXH3 streaming in near future.

**Comment by azhmur** [comment]
Closed by https://github.com/azhmur/xxHash/pull/2
