### ISSUE TITLE
XXHash streaming result

### ISSUE THREAD

**Issue by odysseus1973** [azhmur/xxHash3#3]
Hello!

This is not issue but question.
Since the library didn't have stream support before, I used another library  XXHash3.NET 2.1.0 by Crauzer.
This library gives completely different results compared to yours when I use XXHash3_64 with streaming.
I would like to understand which result is correct. When I hashing string, the results are identical

Thank you so much for a great library

**Comment by azhmur** [comment]
I had found this issue during my experiments with other implementations. You can run my test:
https://github.com/azhmur/xxHash/blob/master/Tests/Program.cs#L15

Right now there are bunch of unit tests in my implementation which compare result between native reference implementation (which had passed SMHasher) and both my streaming and non streaming implementations. So I'm quite sure it works the same way as reference implementation.
As for the other implementations, I can see two possible reasons:
1) xxHash3 has changed multiple times during its development. So they may implemented some older version of it.
2) There can be just bugs as well.
